### ISSUE TITLE
Docker compose error on Arch

### ISSUE THREAD

**Issue by filippo-ferrando** [Elemento-Modular-Cloud/helpcenter#11]
OS: Arch linux 6.8.6
App: Elemento_Cloud_App_linux_x86.AppImage

When i tried to run the daemons with ```sudo -i``` then ```docker-compose up -d``` one container gives unhealthy error

![Screenshot from 2024-04-18 11-11-21](https://github.com/Elemento-Modular-Cloud/helpcenter/assets/55100628/30f88585-6a95-4ced-b664-b60c7b816b21)

Traceback of the error:
```
FileNotFoundError: [Errno 2] No such file or directory: '/root/.elemento/elemento-uuids/elemento-authenticator-client/.clientUUID'
Traceback (most recent call last):
  File "/opt/elemento/elemento-authenticator-client/authenticatorclient.py", line 347, in <module>
    cln = elementoAuthClient()
          ^^^^^^^^^^^^^^^^^^^^
  File "/opt/elemento/elemento-authenticator-client/authenticatorclient.py", line 78, in __init__
    with open(UUID_FILE_NAME, "wb") as file:
		^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by fvalle1** [comment]
why `docker-compose.yml` is in Downloads?
Did you pull the repo?

**Comment by filippo-ferrando** [comment]
I misunderstood the installation process, i only downloaded the ```docker-compose.yml``` file thinking it was the only necessary file.
Retried the installation with the whole ```client``` folder solved the issue
