### ISSUE TITLE
Daemons error

### ISSUE THREAD

**Issue by filippo-ferrando** [Elemento-Modular-Cloud/helpcenter#14]
- OS: Windows
- App: Element_Cloud_App_Win.exe

After launching the services successfully electrOS is not able to comunicate with the daemons giving a ```ERR_CONNECTION_REFUSED``` on the port ```17777, 27777, 37777``` on localhost

**Comment by fvalle1** [comment]
Are you able to open `http://localhost:17777` in the browser?

**Comment by fvalle1** [comment]
May you try to disable the firewall?

**Comment by fvalle1** [comment]
Please update the daemons from https://repo.elemento.cloud/app/Elemento_daemons.zip
