### ISSUE TITLE
Elemento CLI error

### ISSUE THREAD

**Issue by filippo-ferrando** [Elemento-Modular-Cloud/helpcenter#15]
- OS: MacOS Ventura
- App: Elemento_Cloud_App_Mac.dmg

After installing the package with ```pip3 install elemento-cli``` from the terminal i can't use the tool.
Everytime i try to launch the command ```elemento``` the machine responds ```command not found```
Also i have tried the ```python3 -m elemento version``` syntax but the error remains

**Comment by fvalle1** [comment]
Have you tried with virtualenv?

**Comment by filippo-ferrando** [comment]
> Have you tried with virtualenv?

Yes, but with no luck, i keep getting the same error

**Comment by filippo-ferrando** [comment]
I re-tried now to install the `elemento-cli` qith `venv`, i followed this steps:
- `python3 -m venv elemento-venv`
- `source elemento-venv/bin/activate`
- `python3 -m pip install elemento-cli`
And now i can access the cli from my Mac.
