### ISSUE TITLE
APP - Guacamole - 2nd VM viewer doesn't work

### ISSUE THREAD

**Issue by MMogna** [Elemento-Modular-Cloud/helpcenter#2]
If i have two VMs created guacamole doesn't let me see the 2nd one, but just the 1st one. 
<img width="1830" alt="Schermata 2023-07-24 alle 15 14 11" src="https://github.com/Elemento-Modular-Cloud/helpcenter/assets/132584102/eed5cc9c-487c-4206-a80a-184767d4e893">

**Comment by fvalle1** [comment]
Solved with smart tools
