### ISSUE TITLE
Can't create VM with ElectrOs

### ISSUE THREAD

**Issue by filippo-ferrando** [Elemento-Modular-Cloud/helpcenter#21]
I tried to create a custom vm with the smallest amount of resource possible but when i try to register it the `elemento-matcher-client` responds with 
![Screenshot from 2024-04-29 20-08-17](https://github.com/Elemento-Modular-Cloud/helpcenter/assets/55100628/be9d0342-40f8-49ad-a0cd-5870295a1c4c)
And clearly doesn't create the VM

**Comment by fvalle1** [comment]
Are you sure servers are up and running in your LAN?
