### ISSUE TITLE
(ElectrOS) Set of ram

### ISSUE THREAD

**Issue by nicolagutierrez** [Elemento-Modular-Cloud/helpcenter#33]
If the slider of the RAM is not specified (leave the default 256MB), no value is set (at least in the graphical view in the last page).

**Comment by francescochiapello** [comment]
Hi @nicolagutierrez , as per screenshot below, the 250MB size is correctly listed in the resume section at the end of the Advanced creation process.



![Image](https://github.com/Elemento-Modular-Cloud/helpcenter/assets/66141366/029b7a02-547f-4189-adf9-9f157608ebda)

**Comment by fvalle1** [comment]
@francescochiapello may you verify that it is also correct in the payload of the request?

**Comment by francescochiapello** [comment]
Yes, I confirm. In both /canallocate and /register the value is correctly set  `ramsize: 256` for 250MB
