### ISSUE TITLE
Cannot run deamons for electros

### ISSUE THREAD

**Issue by C4lopsitta** [Elemento-Modular-Cloud/helpcenter#4]
![image](https://github.com/Elemento-Modular-Cloud/helpcenter/assets/75886577/94ef0441-4c63-4002-9a3a-ee155f924c12)
I tried running the daemons for electros from the release 1.0 package but it fails with `docker-compose up`

**Comment by fvalle1** [comment]
Hi @C4lopsitta i noticed that `PWD variable is not set`
you have to run it from a *root* sheel

try `sudo -i`
then `docker compose up -d`
