### ISSUE TITLE
ElecrOS authentication bug

### ISSUE THREAD

**Issue by Marco-Garro** [Elemento-Modular-Cloud/helpcenter#40]
Sometimes when I log into ElectOS it returns me an auth error, but if I try to press enter I can log in properly.
(every test have been done with the correct email and password).

https://github.com/user-attachments/assets/5c44837b-5eca-417f-8aea-299bfaf2cfc8

**Comment by francescochiapello** [comment]
@fvalle1  I cannot reproduce this error unfortunately

The error displayed in the above video is triggered only if the `authenticated` value is false.
```
if (res.ok && res.data.authenticated) {
```

Please, @Marco-Garro contact me directly immediately when this error occours so we could try to debug it better with live screen share. Thank you very much
