### ISSUE TITLE
change image of helpcenter

### ISSUE THREAD

**Issue by filippo-ferrando** [Elemento-Modular-Cloud/helpcenter#44]
actual broken link:
https://raw.githubusercontent.com/Elemento-Modular-Cloud/graphic-assets/main/logos/horizontal/Logo%20horizontal%20lightbg%20transp.svg

correct link:
https://raw.githubusercontent.com/Elemento-Modular-Cloud/graphic-assets/main/logos/OLD/horizontal/Logo%20horizontal%20lightbg%20transp.svg

**Comment by fvalle1** [comment]
thx
