### ISSUE TITLE
File .elemento/settings Configuration not working as intended

### ISSUE THREAD

**Issue by MMogna** [Elemento-Modular-Cloud/helpcenter#8]
OS: macOS Sonoma 14.4.1
Logged onto ElectrOS as MMogna

During my testing of AtomOS on another machine, I endeavored to communicate solely with that specific machine for thorough evaluation. To achieve this, I adjusted the .elemento/hosts file to include only the IP address of that machine and configured the ./elemento/settings file as follows. Despite these modifications, I continue to encounter listings of additional volumes on ElectrOS (and in the CLI) that are linked to a different machine.

<img width="241" alt="Screenshot 2024-04-16 at 10 28 22" src="https://github.com/Elemento-Modular-Cloud/helpcenter/assets/132584102/86757d8c-f351-4ad1-b0e2-e9d1a2b10dd0">

<img width="250" alt="Screenshot 2024-04-16 at 10 28 04" src="https://github.com/Elemento-Modular-Cloud/helpcenter/assets/132584102/f3b64981-d066-4fa9-9df9-0d24c7051e1d">

<img width="1478" alt="Screenshot 2024-04-16 at 10 27 36" src="https://github.com/Elemento-Modular-Cloud/helpcenter/assets/132584102/1a7e1a1c-b88a-46c0-b2ac-f87cb72edc5d">

the daemons are launched using this commands into a terminal
<img width="583" alt="Screenshot 2024-04-16 at 10 30 16" src="https://github.com/Elemento-Modular-Cloud/helpcenter/assets/132584102/33fa7bc1-2297-4861-94a4-0cc2309a31e2">

**Comment by MMogna** [comment]
I initiated the daemons for the first time after modifying the "settings" and "hosts" files. Upon noticing unexpected volumes appearing in the app, I restarted the daemons and the app, but observed no changes.

**Comment by fvalle1** [comment]
Are you using the latest version of the daemons?

May you download them and retry the whole process?
