### ISSUE TITLE
Docker compose error on Ubuntu 23.10 (VM)

### ISSUE THREAD

**Issue by filippo-ferrando** [Elemento-Modular-Cloud/helpcenter#9]
OS: Ubuntu 23.10 on VM
App: Elemento_Cloud_App_linux_x86.deb

When installing form scratch the compose file, docker gives 3 unhealthy containers ```elemento-network-client```,```elemento-storage-client```,```elemento-matcher-client```.
I tried to launch the compose file with ```sudo``` --> ```sudo docker-compose up``` but this also gives a warning about the PWD variable not set.
I tried with ```sudo -i```,like it was said in issue #4,  with the same result except for the warning.

![Screenshot from 2024-04-17 19-16-03](https://github.com/Elemento-Modular-Cloud/helpcenter/assets/55100628/2efc31ec-d332-43e2-bcbf-187bec525d5b)

**Comment by filippo-ferrando** [comment]
OS: Arch linux 6.8.6
App: Elemento_Cloud_App_linux_x86.AppImage
The same error happen on arch on a different container

![Screenshot from 2024-04-18 11-11-21](https://github.com/Elemento-Modular-Cloud/helpcenter/assets/55100628/30f88585-6a95-4ced-b664-b60c7b816b21)

**Comment by fvalle1** [comment]
May you share the logs of the containers in this case?
